"""Email notification service — sends agent run reports via SMTP."""

import html
import logging

import aiosmtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

from ..config import settings

logger = logging.getLogger(__name__)


def _markdown_to_html(md_text: str) -> str:
    """Convert markdown to HTML for email body."""
    try:
        import markdown as md_lib
        return md_lib.markdown(md_text, extensions=["tables", "fenced_code"])
    except ImportError:
        # Fallback: basic HTML conversion
        escaped = html.escape(md_text)
        return f"<pre style='font-family: sans-serif; white-space: pre-wrap;'>{escaped}</pre>"


async def send_agent_report_email(
    to_email: str,
    agent_name: str,
    run_output_markdown: str,
    run_id: int,
) -> bool:
    """Send agent run output as an email. Returns True on success."""
    if not settings.SMTP_HOST or not settings.SMTP_USER:
        logger.warning("SMTP not configured — skipping email notification")
        return False

    subject = f"Agent Report: {agent_name}"
    html_body = _markdown_to_html(run_output_markdown)

    full_html = f"""\
<html>
<body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; background: #1d232a; color: #a6adbb;">
  <div style="background: #191e24; border-radius: 12px; padding: 24px; border: 1px solid #383f47;">
    <h2 style="color: #7480ff; margin-top: 0;">🤖 Agent Report: {html.escape(agent_name)}</h2>
    <hr style="border-color: #383f47;">
    <div style="line-height: 1.7; font-size: 14px;">{html_body}</div>
    <hr style="border-color: #383f47;">
    <p style="color: #6b7280; font-size: 11px; margin-bottom: 0;">
      Run ID: {run_id} &middot; Generated by FinoAgent.ai AI Agent
    </p>
  </div>
</body>
</html>"""

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.SMTP_FROM or settings.SMTP_USER
    msg["To"] = to_email

    # Plain text fallback
    msg.attach(MIMEText(run_output_markdown, "plain"))
    # HTML version
    msg.attach(MIMEText(full_html, "html"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=settings.SMTP_HOST,
            port=settings.SMTP_PORT,
            username=settings.SMTP_USER,
            password=settings.SMTP_PASS,
            use_tls=settings.SMTP_USE_TLS and settings.SMTP_PORT == 465,
            start_tls=settings.SMTP_USE_TLS and settings.SMTP_PORT != 465,
        )
        logger.info(f"Email sent to {to_email} for agent '{agent_name}' run {run_id}")
        return True
    except Exception as e:
        logger.exception(f"Failed to send email to {to_email}: {e}")
        return False


async def send_waitlist_email(user_email: str) -> bool:
    """Send waitlist signup notification to rahul@finoagent.ai."""
    if not settings.SMTP_HOST or not settings.SMTP_USER:
        logger.warning("SMTP not configured — skipping waitlist notification")
        return False

    if not settings.SMTP_PASS:
        logger.warning(
            "SMTP_PASS is empty — cannot send waitlist notification. "
            "Set SMTP_PASS env var or add it to GCP Secret Manager as 'SMTP_PASS'."
        )
        return False

    logger.info(
        "Sending waitlist email via %s:%d (user=%s, use_tls=%s)",
        settings.SMTP_HOST, settings.SMTP_PORT, settings.SMTP_USER, settings.SMTP_USE_TLS,
    )

    subject = f"New Waitlist Signup: {user_email}"
    text_body = f"A new user has joined the FinoAgent.ai developer waitlist.\n\nTheir email address is: {user_email}"

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = settings.SMTP_FROM or settings.SMTP_USER
    msg["To"] = "rahul@finoagent.ai"

    msg.attach(MIMEText(text_body, "plain"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=settings.SMTP_HOST,
            port=settings.SMTP_PORT,
            username=settings.SMTP_USER,
            password=settings.SMTP_PASS,
            use_tls=settings.SMTP_USE_TLS and settings.SMTP_PORT == 465,
            start_tls=settings.SMTP_USE_TLS and settings.SMTP_PORT != 465,
        )
        logger.info("Waitlist email notification sent for %s", user_email)
        return True
    except Exception as e:
        logger.error(
            "Failed to send waitlist notification for %s: %s  [host=%s port=%d tls=%s]",
            user_email, e, settings.SMTP_HOST, settings.SMTP_PORT, settings.SMTP_USE_TLS,
        )
        return False
