"""baseline — snapshot of the schema as of Alembic introduction.

This migration is NOT meant to be executed against an existing production
database. Prod already contains every table defined here, created over time
by SQLAlchemy's `Base.metadata.create_all()` plus the DIY inline ALTERs that
previously lived in `app/database.py::init_db()`.

How this file is used
---------------------
- On the production DB: `alembic stamp head` writes the version row; this
  `upgrade()` body is never executed there.
- On a fresh/empty DB (new dev machine, CI, disaster recovery):
  `alembic upgrade head` runs this body top-to-bottom to create everything.
- Future schema changes are additive migrations built on top of this revision.

Dialect notes
-------------
- `server_default=sa.text('(CURRENT_TIMESTAMP)')` was emitted by autogen
  against SQLite. `CURRENT_TIMESTAMP` is ANSI SQL and works on PostgreSQL
  as well. Since this file is never executed against prod, dialect-specific
  rendering here is cosmetic.

Revision ID: a1dd97ff3617
Revises:
Create Date: 2026-04-23 11:10:35.609516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1dd97ff3617'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_users_email'), 'allowed_users', ['email'], unique=True)
    op.create_table('api_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_metrics_created_at'), 'api_metrics', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_metrics_provider'), 'api_metrics', ['provider'], unique=False)
    op.create_table('data_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_cache_cache_key'), 'data_cache', ['cache_key'], unique=True)
    op.create_index(op.f('ix_data_cache_expires_at'), 'data_cache', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.Text(), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_thread_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_whatsapp_number'), 'users', ['whatsapp_number'], unique=True)
    op.create_table('agents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('cloned_from_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('send_email_on_run', sa.Boolean(), nullable=False),
    sa.Column('email_report_to', sa.String(length=255), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cloned_from_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_type', sa.String(length=50), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_broker_connections_user_id'), 'broker_connections', ['user_id'], unique=False)
    op.create_table('guru_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('guru_id', sa.String(length=50), nullable=False),
    sa.Column('guru_name', sa.String(length=100), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guru_analyses_ticker'), 'guru_analyses', ['ticker'], unique=False)
    op.create_index(op.f('ix_guru_analyses_user_id'), 'guru_analyses', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_session_id'), 'sessions', ['session_id'], unique=True)
    op.create_table('stock_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_analyses_ticker'), 'stock_analyses', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_analyses_user_id'), 'stock_analyses', ['user_id'], unique=False)
    op.create_table('stock_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_notes_ticker'), 'stock_notes', ['ticker'], unique=False)
    op.create_index(op.f('ix_stock_notes_user_id'), 'stock_notes', ['user_id'], unique=False)
    op.create_table('tlh_saved_portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('tax_rate_pct', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tlh_saved_portfolios_user_id'), 'tlh_saved_portfolios', ['user_id'], unique=False)
    op.create_table('tracked_companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('theme_raw', sa.Text(), nullable=False),
    sa.Column('theme_slug', sa.String(length=80), nullable=False),
    sa.Column('theme_summary', sa.Text(), nullable=True),
    sa.Column('exchange', sa.String(length=30), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('llm_data', sa.Text(), nullable=False),
    sa.Column('financial_data', sa.Text(), nullable=True),
    sa.Column('last_price_refresh', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.Column('source_tier', sa.String(length=20), nullable=True),
    sa.Column('depth_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_companies_user_id'), 'tracked_companies', ['user_id'], unique=False)
    op.create_table('user_api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('output', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_connection_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('strategy', sa.String(length=100), nullable=False),
    sa.Column('order_data', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('broker_order_ids', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_connection_id'], ['broker_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_orders_user_id'), 'broker_orders', ['user_id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tlh_saved_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['tlh_saved_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('parameters', sa.Text(), nullable=False),
    sa.Column('legs_data', sa.Text(), nullable=False),
    sa.Column('result_snapshot', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('trade_status', sa.String(length=20), nullable=True),
    sa.Column('entry_prices', sa.Text(), nullable=True),
    sa.Column('entry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_net_debit', sa.Float(), nullable=True),
    sa.Column('order_source', sa.String(length=20), nullable=True),
    sa.Column('broker_order_id', sa.Integer(), nullable=True),
    sa.Column('exit_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_prices', sa.Text(), nullable=True),
    sa.Column('exit_net', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['broker_order_id'], ['broker_orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_strategies_trade_status'), 'saved_strategies', ['trade_status'], unique=False)
    op.create_index(op.f('ix_saved_strategies_user_id'), 'saved_strategies', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_saved_strategies_user_id'), table_name='saved_strategies')
    op.drop_index(op.f('ix_saved_strategies_trade_status'), table_name='saved_strategies')
    op.drop_table('saved_strategies')
    op.drop_table('tlh_saved_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_broker_orders_user_id'), table_name='broker_orders')
    op.drop_table('broker_orders')
    op.drop_table('agent_runs')
    op.drop_table('user_api_keys')
    op.drop_index(op.f('ix_tracked_companies_user_id'), table_name='tracked_companies')
    op.drop_table('tracked_companies')
    op.drop_index(op.f('ix_tlh_saved_portfolios_user_id'), table_name='tlh_saved_portfolios')
    op.drop_table('tlh_saved_portfolios')
    op.drop_index(op.f('ix_stock_notes_user_id'), table_name='stock_notes')
    op.drop_index(op.f('ix_stock_notes_ticker'), table_name='stock_notes')
    op.drop_table('stock_notes')
    op.drop_index(op.f('ix_stock_analyses_user_id'), table_name='stock_analyses')
    op.drop_index(op.f('ix_stock_analyses_ticker'), table_name='stock_analyses')
    op.drop_table('stock_analyses')
    op.drop_index(op.f('ix_sessions_session_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_guru_analyses_user_id'), table_name='guru_analyses')
    op.drop_index(op.f('ix_guru_analyses_ticker'), table_name='guru_analyses')
    op.drop_table('guru_analyses')
    op.drop_index(op.f('ix_broker_connections_user_id'), table_name='broker_connections')
    op.drop_table('broker_connections')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_whatsapp_number'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_data_cache_expires_at'), table_name='data_cache')
    op.drop_index(op.f('ix_data_cache_cache_key'), table_name='data_cache')
    op.drop_table('data_cache')
    op.drop_index(op.f('ix_api_metrics_provider'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_created_at'), table_name='api_metrics')
    op.drop_table('api_metrics')
    op.drop_index(op.f('ix_allowed_users_email'), table_name='allowed_users')
    op.drop_table('allowed_users')
    # ### end Alembic commands ###
